### ISSUE TITLE
No results found when searching by metadata where datatype is an Array

### ISSUE THREAD

**Issue by schlitzauge00** [rokka-io/rokka-dashboard#107]
**How to reproduce**

1.  Add a metadata (ie. name=merchant_sku, datatype=Array, Value=12345, 6789)

**Observed behaviour**
No results found when searching for 12345 in merchant_sku as metadata

**expected behaviour**
Image can be found in regard of the datatype content/format

**Comment by chregu** [comment]
Since it's an array, it also needs the array: prefix eg.
```
{{Host}}/sourceimages/{{Org}}?user:array:merchant_sku=1234
```
Not sure, what the dashboard does in this case. Works with the API this way, at least

**Comment by mweibel** [comment]
@chregu for an array, can you search for more than one value (as in the example, search for 12345 and 6789)?

**Comment by chregu** [comment]
Currently, no (or I don't see how ..). If we would support that, we'd do another syntax like `user:array:merchant_sku[]=1234` in case you want to search for more than one value (which only makes sense for arrays anyway, since we only support AND searches currently)
