### ISSUE TITLE
Stacks can't be created anymore

### ISSUE THREAD

**Issue by KilianSSL** [rokka-io/rokka-dashboard#114]
When i try to save a new stack it seems like it will take forever.
Opening the browser console reveals an error:

`schema is invalid: data.properties['resize_to_primary'].type should be equal to one of the allowed values, data.properties['resize_to_primary'].type should be array, data.properties['resize_to_primary'].type should match some schema in anyOfschema is invalid: data.properties['resize_to_primary'].type should be equal to one of the allowed values, data.properties['resize_to_primary'].type should be array, data.properties['resize_to_primary'].type should match some schema in anyOf at v.validateSchema (ajv.js:196)`

Plattform:
MacOS X / Chrome Version 72.0.3626.109

**Comment by mweibel** [comment]
Thanks. @chregu will fix on API side.

https://api.rokka.io/operations returns `resize_to_primary` type as `bool` but according to specs it should be `boolean`.

**Comment by mweibel** [comment]
fixed.
