### ISSUE TITLE
Stack Form won't let me check input="checkbox" values

### ISSUE THREAD

**Issue by KilianSSL** [rokka-io/rokka-dashboard#117]
Despite the form element being not disabled, i can't check the checkboxes.

Chrome Version 74.0.3729.157 / Mac OS

![image](https://user-images.githubusercontent.com/5079898/58164222-b2934000-7c85-11e9-8bdf-70912b8a5628.png)

**Comment by mweibel** [comment]
hrm. Nice catch. will investigate.
