### ISSUE TITLE
Improve thumbnails on overview (especially for videos)

### ISSUE THREAD

**Issue by chregu** [rokka-io/rokka-dashboard#84]
As we now support videos (kinda), the thumbnails in the dashboard overview are empty for those. Even worse, since we link to the *.mp4 version in that case, the browser downloads that.

Also in general, we always download the full resolution on the image for the overview. Would be great, if we could resize that to the actual needed values and change the ending for videos. If you use "png" or "jpg" for a video, it will display a thumbnail.

Or maybe even better, just use ".jpg" for "image/jpeg" and ".png" for everything else (due to alpha channel issues). Shouldn't matter much size related with the size of the thumbnails (as long as you also resize them to the preview size)

**Comment by mweibel** [comment]
Done :)
