### ISSUE TITLE
Wrong values for image quality in stack

### ISSUE THREAD

**Issue by dulnan** [rokka-io/rokka-dashboard#96]
I have several stacks with different image quality settings. The stacks follow a naming scheme of text_width_height_density, e.g. tiny_64_64_1 and tiny_64_64_2. When I open the first stack, the values for image quality are correct. In the second one (tiny_64_64_2), the values are wrong. They show the values for *the other* stack (tiny_64_64_1).
![9b981918-42f2-4cee-9f6d-983d71393972](https://user-images.githubusercontent.com/4155003/47697793-e71dac80-dc0c-11e8-8463-b0720e7419a3.png)

**Comment by mweibel** [comment]
Thanks for the report.
Does it only happen if you open first _1, then _2 or also if you open _2 directly?
